import { images } from "@/src/assets/images";
import { StaticImageData } from "next/image";
import { IProductItem } from "../product/data";

export interface ICollectionItem {
  id: number;
  title: string;
  year: number;
  season: string;
  category: string;
  price: number;
  author: string;
  author_img: string | StaticImageData;
  design_ideas: string[];
  desc: string;
  slug: string;
  product: IProductItem[];
  thumbnail: string | StaticImageData;
}

export const COLLECTIONS_DATA: ICollectionItem[] = [
  {
    id: 1,
    title: "Brutalist Beauty",
    slug: "brutalist-beauty",
    year: 2024,
    season: "Xuân/Hè",
    category: "Couture",
    price: 15000000,
    thumbnail: images.collection1,
    product: [
      {
        id: "1",
        title: "Blazer Len Cấu Trúc",
        slug: "blazer-len-cau-truc",
        label: "Than Chì / Len Thô",
        category_product: "outerwear",
        desc: "Thiết kế blazer cấu trúc sắc nét mang lại vẻ ngoài thanh lịch và quyền lực. Chất liệu len thô cao cấp giúp giữ form hoàn hảo, phù hợp cho cả môi trường công sở lẫn những dịp quan trọng.",
        price: 1240,
        thumbnail: images.collection1,
        gallery: [
          images.collection1,
          images.collection6,
          images.collection5,
          images.collection4,
        ],
      },
      {
        id: "2",
        title: "Váy Lụa Mềm Mại",
        slug: "vay-lua-mem-mai",
        label: "Ngọc Trai / Lụa Mulberry",
        category_product: "outerwear",
        desc: "Chiếc váy lụa Mulberry cao cấp với độ rũ tự nhiên, tạo cảm giác nhẹ nhàng và sang trọng. Từng chuyển động đều tôn lên nét nữ tính tinh tế và cuốn hút.",
        price: 2800,
        thumbnail: images.collection2,
        gallery: [
          images.collection2,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "3",
        title: "Quần Tây Thiết Kế Dáng Ôm",
        slug: "quan-tay-thiet-ke-dang-om",
        label: "Đen Obsidian / Twill",
        category_product: "outerwear",
        desc: "Phom dáng ôm gọn gàng giúp tôn lên đường nét cơ thể, kết hợp cùng chất liệu twill bền đẹp. Lựa chọn lý tưởng cho phong cách hiện đại và chuyên nghiệp.",
        price: 890,
        thumbnail: images.collection3,
        gallery: [
          images.collection3,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "4",
        title: "Áo Khoác Trench Điêu Khắc",
        slug: "ao-khoac-trench-dieu-khac",
        label: "Cát Sa Mạc / Gabardine",
        category_product: "outerwear",
        desc: "Thiết kế trench coat mang cảm hứng điêu khắc, tạo nên vẻ ngoài mạnh mẽ và đầy khí chất. Chất liệu gabardine chống gió tốt, phù hợp cho những ngày thời tiết chuyển mùa.",
        price: 3450,
        thumbnail: images.collection4,
        gallery: [
          images.collection4,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "5",
        title: "Áo Vest Len Tối Giản",
        slug: "ao-vest-len-toi-gian",
        label: "Xanh Olive Đậm / Cashmere",
        category_product: "outerwear",
        desc: "Chiếc vest tối giản với chất liệu cashmere mềm mại, mang lại cảm giác ấm áp và tinh tế. Phù hợp cho phong cách layering hiện đại và sang trọng.",
        price: 420,
        thumbnail: images.collection5,
        gallery: [
          images.collection5,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
    ],
    desc: "Mẫu đầm dạ hội mang tính biểu tượng với kỹ thuật đính kết thủ công pha lê và hạt cườm siêu nhỏ trong suốt hơn 200 giờ làm việc liên tục.",
    author: "Alexandre Vu",
    author_img: images.collection,
    design_ideas: [
      "Lấy cảm hứng từ kiến trúc Brutalism...",
      "Sự kết hợp táo bạo giữa cắt xẻ và đính kết...",
    ],
  },
  {
    id: 2,
    title: "Midnight Silhouette",
    slug: "midnight-silhouette",
    year: 2024,
    season: "Thu/Đông",
    category: "Couture",
    price: 32000000,
    thumbnail: images.collection5,
    product: [
      {
        id: "2",
        title: "Váy Lụa Mềm Mại",
        slug: "vay-lua-mem-mai",
        label: "Ngọc Trai / Lụa Mulberry",
        category_product: "outerwear",
        desc: "Chiếc váy lụa Mulberry cao cấp với độ rũ tự nhiên, tạo cảm giác nhẹ nhàng và sang trọng. Từng chuyển động đều tôn lên nét nữ tính tinh tế và cuốn hút.",
        price: 2800,
        thumbnail: images.collection2,
        gallery: [
          images.collection2,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "3",
        title: "Quần Tây Thiết Kế Dáng Ôm",
        slug: "quan-tay-thiet-ke-dang-om",
        label: "Đen Obsidian / Twill",
        category_product: "outerwear",
        desc: "Phom dáng ôm gọn gàng giúp tôn lên đường nét cơ thể, kết hợp cùng chất liệu twill bền đẹp. Lựa chọn lý tưởng cho phong cách hiện đại và chuyên nghiệp.",
        price: 890,
        thumbnail: images.collection3,
        gallery: [
          images.collection3,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "4",
        title: "Áo Khoác Trench Điêu Khắc",
        slug: "ao-khoac-trench-dieu-khac",
        label: "Cát Sa Mạc / Gabardine",
        category_product: "outerwear",
        desc: "Thiết kế trench coat mang cảm hứng điêu khắc, tạo nên vẻ ngoài mạnh mẽ và đầy khí chất. Chất liệu gabardine chống gió tốt, phù hợp cho những ngày thời tiết chuyển mùa.",
        price: 3450,
        thumbnail: images.collection4,
        gallery: [
          images.collection4,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "5",
        title: "Áo Vest Len Tối Giản",
        slug: "ao-vest-len-toi-gian",
        label: "Xanh Olive Đậm / Cashmere",
        category_product: "outerwear",
        desc: "Chiếc vest tối giản với chất liệu cashmere mềm mại, mang lại cảm giác ấm áp và tinh tế. Phù hợp cho phong cách layering hiện đại và sang trọng.",
        price: 420,
        thumbnail: images.collection5,
        gallery: [
          images.collection5,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "6",
        title: "Quần Palazzo",
        slug: "quan-palazzo",
        label: "Ngà Voi / Hỗn Hợp Linen",
        category_product: "outerwear",
        desc: "Quần palazzo ống rộng với chất liệu linen thoáng mát, tạo sự thoải mái tối đa khi mặc. Thiết kế bay bổng giúp tôn lên vẻ thanh lịch và thời thượng.",
        price: 1100,
        thumbnail: images.collection6,
        gallery: [
          images.collection6,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
    ],
    desc: "Sự kết hợp hoàn mỹ giữa chất liệu nhung lụa Ý cao cấp và kỹ thuật dựng form corset kiến trúc đỉnh cao.",
    author: "Elena Tran",
    author_img: images.collection,
    design_ideas: [
      "Khai thác vẻ đẹp huyền bí của màn đêm...",
      "Ứng dụng kỹ thuật dựng khung xương corset Pháp...",
    ],
  },
  {
    id: 3,
    title: "The Urban Tailor",
    slug: "the-urban-tailor",
    year: 2024,
    season: "Xuân/Hè",
    category: "Ready-to-wear",
    price: 4500000,
    thumbnail: images.collection4,
    product: [
      {
        id: "2",
        title: "Váy Lụa Mềm Mại",
        slug: "vay-lua-mem-mai",
        label: "Ngọc Trai / Lụa Mulberry",
        category_product: "outerwear",
        desc: "Chiếc váy lụa Mulberry cao cấp với độ rũ tự nhiên, tạo cảm giác nhẹ nhàng và sang trọng. Từng chuyển động đều tôn lên nét nữ tính tinh tế và cuốn hút.",
        price: 2800,
        thumbnail: images.collection2,
        gallery: [
          images.collection2,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "3",
        title: "Quần Tây Thiết Kế Dáng Ôm",
        slug: "quan-tay-thiet-ke-dang-om",
        label: "Đen Obsidian / Twill",
        category_product: "outerwear",
        desc: "Phom dáng ôm gọn gàng giúp tôn lên đường nét cơ thể, kết hợp cùng chất liệu twill bền đẹp. Lựa chọn lý tưởng cho phong cách hiện đại và chuyên nghiệp.",
        price: 890,
        thumbnail: images.collection3,
        gallery: [
          images.collection3,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "4",
        title: "Áo Khoác Trench Điêu Khắc",
        slug: "ao-khoac-trench-dieu-khac",
        label: "Cát Sa Mạc / Gabardine",
        category_product: "outerwear",
        desc: "Thiết kế trench coat mang cảm hứng điêu khắc, tạo nên vẻ ngoài mạnh mẽ và đầy khí chất. Chất liệu gabardine chống gió tốt, phù hợp cho những ngày thời tiết chuyển mùa.",
        price: 3450,
        thumbnail: images.collection4,
        gallery: [
          images.collection4,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "5",
        title: "Áo Vest Len Tối Giản",
        slug: "ao-vest-len-toi-gian",
        label: "Xanh Olive Đậm / Cashmere",
        category_product: "outerwear",
        desc: "Chiếc vest tối giản với chất liệu cashmere mềm mại, mang lại cảm giác ấm áp và tinh tế. Phù hợp cho phong cách layering hiện đại và sang trọng.",
        price: 420,
        thumbnail: images.collection5,
        gallery: [
          images.collection5,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "6",
        title: "Quần Palazzo",
        slug: "quan-palazzo",
        label: "Ngà Voi / Hỗn Hợp Linen",
        category_product: "outerwear",
        desc: "Quần palazzo ống rộng với chất liệu linen thoáng mát, tạo sự thoải mái tối đa khi mặc. Thiết kế bay bổng giúp tôn lên vẻ thanh lịch và thời thượng.",
        price: 1100,
        thumbnail: images.collection6,
        gallery: [
          images.collection6,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
    ],
    desc: "Tái định nghĩa phong cách công sở hiện đại với thiết kế áo Blazer oversized được cắt may chuẩn xác.",
    author: "Minh Pham",
    author_img: images.collection,
    design_ideas: [
      "Giao thoa giữa menswear cổ điển và tự do hiện đại...",
      "Tập trung vào cấu trúc vai và công năng...",
    ],
  },
  {
    id: 4,
    title: "Ethereal Drape",
    slug: "ethereal-drape",
    year: 2023,
    season: "Xuân/Hè",
    category: "Couture",
    price: 18500000,
    thumbnail: images.collection1,
    product: [
      {
        id: "2",
        title: "Váy Lụa Mềm Mại",
        slug: "vay-lua-mem-mai",
        label: "Ngọc Trai / Lụa Mulberry",
        category_product: "outerwear",
        desc: "Chiếc váy lụa Mulberry cao cấp với độ rũ tự nhiên, tạo cảm giác nhẹ nhàng và sang trọng. Từng chuyển động đều tôn lên nét nữ tính tinh tế và cuốn hút.",
        price: 2800,
        thumbnail: images.collection2,
        gallery: [
          images.collection2,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "3",
        title: "Quần Tây Thiết Kế Dáng Ôm",
        slug: "quan-tay-thiet-ke-dang-om",
        label: "Đen Obsidian / Twill",
        category_product: "outerwear",
        desc: "Phom dáng ôm gọn gàng giúp tôn lên đường nét cơ thể, kết hợp cùng chất liệu twill bền đẹp. Lựa chọn lý tưởng cho phong cách hiện đại và chuyên nghiệp.",
        price: 890,
        thumbnail: images.collection3,
        gallery: [
          images.collection3,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "4",
        title: "Áo Khoác Trench Điêu Khắc",
        slug: "ao-khoac-trench-dieu-khac",
        label: "Cát Sa Mạc / Gabardine",
        category_product: "outerwear",
        desc: "Thiết kế trench coat mang cảm hứng điêu khắc, tạo nên vẻ ngoài mạnh mẽ và đầy khí chất. Chất liệu gabardine chống gió tốt, phù hợp cho những ngày thời tiết chuyển mùa.",
        price: 3450,
        thumbnail: images.collection4,
        gallery: [
          images.collection4,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "5",
        title: "Áo Vest Len Tối Giản",
        slug: "ao-vest-len-toi-gian",
        label: "Xanh Olive Đậm / Cashmere",
        category_product: "outerwear",
        desc: "Chiếc vest tối giản với chất liệu cashmere mềm mại, mang lại cảm giác ấm áp và tinh tế. Phù hợp cho phong cách layering hiện đại và sang trọng.",
        price: 420,
        thumbnail: images.collection5,
        gallery: [
          images.collection5,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "6",
        title: "Quần Palazzo",
        slug: "quan-palazzo",
        label: "Ngà Voi / Hỗn Hợp Linen",
        category_product: "outerwear",
        desc: "Quần palazzo ống rộng với chất liệu linen thoáng mát, tạo sự thoải mái tối đa khi mặc. Thiết kế bay bổng giúp tôn lên vẻ thanh lịch và thời thượng.",
        price: 1100,
        thumbnail: images.collection6,
        gallery: [
          images.collection6,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
    ],
    desc: "Sử dụng kỹ thuật draping bậc thầy trực tiếp trên mannequin với chất liệu lụa Chiffon tơ tằm cao cấp.",
    author: "Julianne Le",
    author_img: images.brand,
    design_ideas: [
      "Mô phỏng sự chuyển động của dòng chảy...",
      "Khai thác đặc tính xuyên thấu của lụa...",
    ],
  },
  {
    id: 5,
    title: "Heritage Weave",
    slug: "heritage-weave",
    year: 2023,
    season: "Thu/Đông",
    category: "Ready-to-wear",
    price: 6800000,
    thumbnail: images.collection5,
    product: [
      {
        id: "2",
        title: "Váy Lụa Mềm Mại",
        slug: "vay-lua-mem-mai",
        label: "Ngọc Trai / Lụa Mulberry",
        category_product: "outerwear",
        desc: "Chiếc váy lụa Mulberry cao cấp với độ rũ tự nhiên, tạo cảm giác nhẹ nhàng và sang trọng. Từng chuyển động đều tôn lên nét nữ tính tinh tế và cuốn hút.",
        price: 2800,
        thumbnail: images.collection2,
        gallery: [
          images.collection2,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "3",
        title: "Quần Tây Thiết Kế Dáng Ôm",
        slug: "quan-tay-thiet-ke-dang-om",
        label: "Đen Obsidian / Twill",
        category_product: "outerwear",
        desc: "Phom dáng ôm gọn gàng giúp tôn lên đường nét cơ thể, kết hợp cùng chất liệu twill bền đẹp. Lựa chọn lý tưởng cho phong cách hiện đại và chuyên nghiệp.",
        price: 890,
        thumbnail: images.collection3,
        gallery: [
          images.collection3,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "4",
        title: "Áo Khoác Trench Điêu Khắc",
        slug: "ao-khoac-trench-dieu-khac",
        label: "Cát Sa Mạc / Gabardine",
        category_product: "outerwear",
        desc: "Thiết kế trench coat mang cảm hứng điêu khắc, tạo nên vẻ ngoài mạnh mẽ và đầy khí chất. Chất liệu gabardine chống gió tốt, phù hợp cho những ngày thời tiết chuyển mùa.",
        price: 3450,
        thumbnail: images.collection4,
        gallery: [
          images.collection4,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "5",
        title: "Áo Vest Len Tối Giản",
        slug: "ao-vest-len-toi-gian",
        label: "Xanh Olive Đậm / Cashmere",
        category_product: "outerwear",
        desc: "Chiếc vest tối giản với chất liệu cashmere mềm mại, mang lại cảm giác ấm áp và tinh tế. Phù hợp cho phong cách layering hiện đại và sang trọng.",
        price: 420,
        thumbnail: images.collection5,
        gallery: [
          images.collection5,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "6",
        title: "Quần Palazzo",
        slug: "quan-palazzo",
        label: "Ngà Voi / Hỗn Hợp Linen",
        category_product: "outerwear",
        desc: "Quần palazzo ống rộng với chất liệu linen thoáng mát, tạo sự thoải mái tối đa khi mặc. Thiết kế bay bổng giúp tôn lên vẻ thanh lịch và thời thượng.",
        price: 1100,
        thumbnail: images.collection6,
        gallery: [
          images.collection6,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
    ],
    desc: "Sự kết hợp độc đáo giữa chất liệu Tweed dệt tay truyền thống và các chi tiết kim loại hiện đại.",
    author: "Quoc Nguyen",
    author_img: images.brand,
    design_ideas: [
      "Tôn vinh bàn tay nghệ nhân làng nghề...",
      "Tạo tương phản giữa kim loại và vải dệt...",
    ],
  },
  {
    id: 6,
    title: "Avant-Garde Structure",
    slug: "avant-garde-structure",
    year: 2022,
    season: "Thu/Đông",
    category: "Couture",
    price: 45000000,
    thumbnail: images.collection3,
    product: [
      {
        id: "2",
        title: "Váy Lụa Mềm Mại",
        slug: "vay-lua-mem-mai",
        label: "Ngọc Trai / Lụa Mulberry",
        category_product: "outerwear",
        desc: "Chiếc váy lụa Mulberry cao cấp với độ rũ tự nhiên, tạo cảm giác nhẹ nhàng và sang trọng. Từng chuyển động đều tôn lên nét nữ tính tinh tế và cuốn hút.",
        price: 2800,
        thumbnail: images.collection2,
        gallery: [
          images.collection2,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "3",
        title: "Quần Tây Thiết Kế Dáng Ôm",
        slug: "quan-tay-thiet-ke-dang-om",
        label: "Đen Obsidian / Twill",
        category_product: "outerwear",
        desc: "Phom dáng ôm gọn gàng giúp tôn lên đường nét cơ thể, kết hợp cùng chất liệu twill bền đẹp. Lựa chọn lý tưởng cho phong cách hiện đại và chuyên nghiệp.",
        price: 890,
        thumbnail: images.collection3,
        gallery: [
          images.collection3,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "4",
        title: "Áo Khoác Trench Điêu Khắc",
        slug: "ao-khoac-trench-dieu-khac",
        label: "Cát Sa Mạc / Gabardine",
        category_product: "outerwear",
        desc: "Thiết kế trench coat mang cảm hứng điêu khắc, tạo nên vẻ ngoài mạnh mẽ và đầy khí chất. Chất liệu gabardine chống gió tốt, phù hợp cho những ngày thời tiết chuyển mùa.",
        price: 3450,
        thumbnail: images.collection4,
        gallery: [
          images.collection4,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "5",
        title: "Áo Vest Len Tối Giản",
        slug: "ao-vest-len-toi-gian",
        label: "Xanh Olive Đậm / Cashmere",
        category_product: "outerwear",
        desc: "Chiếc vest tối giản với chất liệu cashmere mềm mại, mang lại cảm giác ấm áp và tinh tế. Phù hợp cho phong cách layering hiện đại và sang trọng.",
        price: 420,
        thumbnail: images.collection5,
        gallery: [
          images.collection5,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
      {
        id: "6",
        title: "Quần Palazzo",
        slug: "quan-palazzo",
        label: "Ngà Voi / Hỗn Hợp Linen",
        category_product: "outerwear",
        desc: "Quần palazzo ống rộng với chất liệu linen thoáng mát, tạo sự thoải mái tối đa khi mặc. Thiết kế bay bổng giúp tôn lên vẻ thanh lịch và thời thượng.",
        price: 1100,
        thumbnail: images.collection6,
        gallery: [
          images.collection6,
          images.collection2,
          images.collection3,
          images.collection4,
        ],
      },
    ],
    desc: "Một tác phẩm nghệ thuật mang tính thể nghiệm cao với cấu trúc không gian 3D phức tạp.",
    author: "Victor Hoang",
    author_img: images.brand,
    design_ideas: [
      "Phá bỏ quy chuẩn phom dáng truyền thống...",
      "Ứng dụng công nghệ in 3D và vải bóng...",
    ],
  },
];

// Data cho các nút Filter (Để map ra thanh menu như ảnh)
export const FILTER_OPTIONS = {
  years: ["Tất cả", 2024, 2023, 2022, 2021, 2020],
  seasons: ["Xuân/Hè", "Thu/Đông"],
  categories: ["Couture", "Ready-to-wear"],
};
